//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MI9Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSONSchemaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSONSchemaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MI9Project.JSONSchemaRes", typeof(JSONSchemaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;object&quot;,&quot;$schema&quot;: &quot;http://json-schema.org/draft-03/schema&quot;,&quot;title&quot;: &quot;zx&quot;,&quot;name&quot;: &quot;zx&quot;,&quot;id&quot;: &quot;http://jsonschema.net&quot;,&quot;required&quot;:false,&quot;properties&quot;:{ &quot;payload&quot;: { &quot;type&quot;:&quot;array&quot;, &quot;id&quot;: &quot;http://jsonschema.net/payload&quot;, &quot;required&quot;:true, &quot;items&quot;: { &quot;type&quot;:&quot;object&quot;, &quot;id&quot;: &quot;http://jsonschema.net/payload/0&quot;, &quot;required&quot;:false, &quot;properties&quot;:{ &quot;country&quot;: { &quot;type&quot;:&quot;string&quot;, &quot;id&quot;: &quot;http://jsonschema.net/payload/0/country&quot;, &quot;required&quot;:false }, &quot;description&quot;: { &quot;type&quot;:&quot;string&quot;, &quot;id&quot;: &quot;http://jsonschema.net/paylo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayloadSchema {
            get {
                return ResourceManager.GetString("PayloadSchema", resourceCulture);
            }
        }
    }
}
